title: ZEUNQUSZ ANALYSIS HUB
description: A simple Jekyll site using Monophase theme.
baseurl: "" # 사이트 URL 설정
url: "https://your-username.github.io" # 본인의 GitHub Pages 주소

plugins:
  - jekyll-remote-theme

remote_theme: zivhub/monophase@main
